web/config/routes.rb
SwordOfTheSprit::Application.routes.draw do

  resources :words

end

web/app/models/word.rb
class Word < ActiveRecord::Base
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :ok }
    end
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/words_helper.rb
module WordsHelper
end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwordOfTheSprit</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :paragraph %><br />
    <%= f.text_field :paragraph %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.select :tag, ["복음", "양육", "제자의 삶", "군사의 삶", "재생산의 삶"] %>
  </div>
  <div class="field">
    <%= f.label :prefix %><br />
    <%= f.text_field :prefix %>
  </div>
  <div class="field">
    <%= f.label :memorized %><br />
    <%= f.number_field :memorized %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

web/app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Paragraph</th>
    <th>Note</th>
    <th>Tag</th>
    <th>Prefix</th>
    <th>Memorized</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.subject %></td>
    <td><%= word.paragraph %></td>
    <td><%= word.note %></td>
    <td><%= word.tag %></td>
    <td><%= word.prefix %></td>
    <td><%= word.memorized %></td>
    <td><%= word.priority %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

web/app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

web/app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @word.subject %>
</p>

<p>
  <b>Paragraph:</b>
  <%= @word.paragraph %>
</p>

<p>
  <b>Note:</b>
  <%= @word.note %>
</p>

<p>
  <b>Tag:</b>
  <%= @word.tag %>
</p>

<p>
  <b>Prefix:</b>
  <%= @word.prefix %>
</p>

<p>
  <b>Memorized:</b>
  <%= @word.memorized %>
</p>

<p>
  <b>Priority:</b>
  <%= @word.priority %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>